### ISSUE TITLE
Trains that split or merge

### ISSUE THREAD

**Issue by Bertware** [linkedconnections/gtfs2lc#41]
The NMBS operates several trains which are split into two indepent trains at some point in their journey. The reverse situation also occurs, with two trains merging into one. Splitting or merging always takes place in a station where traveller can (dis)embark the train.

### Splitting

First of all, the train drives the first part of its journey as a whole, during which it is identified by a single identifier, in this case IC4310. When the train splits, one part of the train keeps the identifier (IC4310) for the remaining of its journey. The other part gets a new identifier, in this case (IC4410). Even though it is clear to see that this is one train, even the NMBS website indicates that there are 2 trips. This causes routeplanning to think a transfer is needed, even though travellers can remain seated if they are in the right part of the train. NMBS' own routeplanning takes this into account, but we need a way to determine this for 3rd party routeplanning.  NMBS does not publish data on which carriages travel where.

![splitting train](https://user-images.githubusercontent.com/1094793/42035126-715c34c0-7ae2-11e8-874e-9dd97635f98a.png)
![splitting train](https://user-images.githubusercontent.com/1094793/42035128-718809ec-7ae2-11e8-9a9b-fc644ddac5ba.png)

IC4310 in trips.txt: 

```220,000095,88____:007::8821006:8832409:13:1102:20180625,Hamont,4310,,5481,,1```

IC4410 in trips.txt:

```225,000297,88____:007::8832409:8831005:9:1152:20180625,Hasselt,4410,,5658,,1```
### Merging
Merging trains are similar, and have different identifiers until they merge. Once they merge, one of the trains will continue to travel with the identifier of one of said two trains. It should be noted that the train which loses its identifier on merging doesn't seem to have platform information. Again, routeplanning will consider this as a transer, even though passengers can remain seated (an thus don't have to transfer). NMBS' own routeplanning takes this into account, but we need a way to determine this for 3rd party routeplanning.

![merging train](https://user-images.githubusercontent.com/1094793/42035159-8c206bd2-7ae2-11e8-91e4-2c72f49670c3.png)
![merging train](https://user-images.githubusercontent.com/1094793/42035160-8c4c0d00-7ae2-11e8-831b-e802b4aff8d2.png)

### Solutions for routeplanning
A possible solution for this would be to label the common parts of a journey with both trip ids, by publishing two connection objects for each connection, both objects being identical except for the trip/route id.

Another possible solution would be to create an index of splitting trains, where each row contains two identifiers which belong together in one splitting or merging train. This would be less 'intrusive' to the Linked Connections list, and would prevent certain edge cases (splitting Linked Connections into fragments of a certain filesize could cause two "identical" connections to be split over multiple pages, having to combine and check multiple connection objects would be more complicated compared to only checking a list to determine whether a transfer is 'real' or a split/merge during routeplanning).

Current status
- [x] Investigate how the NMBS handles this
- [x] Investigate how this is published in GTFS

This data is not published in GTFS. There doesn't seem to be any field which implies a train split, or that a train drove part of its journey attached to another train.

**Comment by pietercolpaert** [comment]
> A possible solution for this would be to label the common parts of a journey with both trip ids, by publishing two connection objects for each connection, both objects being identical except for the trip/route id.

I like this idea and would like to pursue it. We should then also explicitly add this to the documentation of the LC specification that more trip IDs are not an exception but very possible with splitting trains.

**Comment by pietercolpaert** [comment]
In GTFS2LC this however gives some trouble in the pipeline, as we do not know that a train e.g., has merged in the past (and thus should have 2 trip ids), or whether a train will split in  the future (and thus these connections also should have 2 trip ids).

**Comment by pietercolpaert** [comment]
I devised a solution by first preprocessing `stop_times.txt`. See https://support.google.com/transitpartners/answer/7084064?hl=en for how GTFS feeds _should_ be designed (not sure whether this is actually the case with  SNCB, will test later).

Example joining train:

trip_id |departure_time| stop_id | pickup_type | drop_off_type | trip_headsign
-- | -- |-- | -- | -- | --
trip_1 |12:00| A | 0 | 0 | E
trip_1 |12:05| B | 0 | 0 | E
trip_1 | 12:10|C | 0 | 0 | E
trip_1 |12:15| D | 0 | 0 | E
trip_1 |12:20| E | 0 | 0 | E
trip_2 | 12:00|X | 0 | 0 | E
trip_2 | 12:05|Y | 0 | 0 | E
trip_2 | 12:10|C | 1 | 0 | E
trip_2 |12:15|D | 1 | 0 | E
trip_2 |12:20| E | 1 | 0 | E

If we first order everything by departuretime and stop_id, the feed will look as follows:

trip_id |departure_time| stop_id | pickup_type | drop_off_type | trip_headsign
-- | -- |-- | -- | -- | --
trip_1 |12:00| A | 0 | 0 | E
trip_2 | 12:00|X | 0 | 0 | E
trip_1 |12:05| B | 0 | 0 | E
trip_2 | 12:05|Y | 0 | 0 | E
trip_1 | 12:10|C | 0 | 0 | E
trip_2 | 12:10|C | 1 ←| 0 | E
trip_1 |12:15| D | 0 | 0 | E
trip_2 |12:15|D | 1 ←| 0 | E
trip_1 |12:20| E | 0 | 0 | E
trip_2 |12:20| E | 1 ←| 0 | E

We will then notice that the same departure_time at the same stop exists, but that one of the  trips is flagged that you  cannot get on the train (but you can get off).

I propose to again preprocess this list and merge both trip ids in one row as follows:

trip_id |departure_time| stop_id | pickup_type | drop_off_type | trip_headsign
-- | -- |-- | -- | -- | --
trip_1 |12:00| A | 0 | 0 | E
trip_2 | 12:00|X | 0 | 0 | E
trip_1 |12:05| B | 0 | 0 | E
trip_2 | 12:05|Y | 0 | 0 | E
trip_1-GTFS2LC-AND-trip_2 | 12:10|C | 0 | 0 | E
trip_1-GTFS2LC-AND-trip_2  |12:15| D | 0 | 0 | E
trip_1-GTFS2LC-AND-trip_2  |12:20| E | 0 | 0 | E

In the code of `stoptimes/st2c.js` we can then always use an array of 1 or more trips instead of always just 1. This array is then also used in the publishing part of Linked Connections.

**Comment by pietercolpaert** [comment]
I just found out that SNCB does not implement this in their GTFS feed… Trying to get in touch with their team.

**Comment by pietercolpaert** [comment]
Fixed in #60. Will need to update the spec slightly to also contain nextConnection predicate instead of only checking gtfs:trip
